/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package EnsEtudFramesPanels;
import java.sql.*;
import MyClasses.*;
import MyFrames.*;

/**
 *
 * @author GLADIATEUR-1650-8
 */
public class ProfPar extends javax.swing.JPanel {
    public Utilisateur user ;
    private static ProfPar instance;
    
    public ProfPar(Utilisateur user) {
        initComponents();
        System.out.println("mlawel "+user.getId()+"  "+nom.getText()+"username "+user.getNom());
        nom.setText(user.getNom());
        prenom.setText(user.getPrenom());
        login.setText(user.getLogin());
        password.setText(user.getPwd());   
        this.user=user;
        
    }
    public static ProfPar getInstance(Utilisateur user){
        if(instance == null){
            return new ProfPar(user);
        }
        return instance;
    }
    public void updateUser(Utilisateur newUser) {
        this.user = newUser;
        System.out.println("updated user :  "+newUser.getId()+"  "+nom.getText()+"username "+newUser.getNom());
        // Update the UI components with the new user information
        nom.setText(user.getNom());
        prenom.setText(user.getPrenom());
        login.setText(user.getLogin());
        password.setText(user.getPwd());
        revalidate();
        repaint();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        prenom = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        login = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        sauvegarder = new javax.swing.JButton();
        redm = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/user.png"))); // NOI18N
        jButton4.setBorder(null);
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 146, 239, 240));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nom");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 74, -1, -1));

        nom.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 109, 327, 50));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Prenom");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 177, -1, -1));

        prenom.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        prenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenomActionPerformed(evt);
            }
        });
        add(prenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 212, 327, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Login");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 280, -1, -1));

        login.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 315, 327, 50));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Mot de passe");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 383, -1, -1));

        password.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 418, 327, 50));

        sauvegarder.setBackground(new java.awt.Color(0, 204, 102));
        sauvegarder.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        sauvegarder.setForeground(new java.awt.Color(255, 255, 255));
        sauvegarder.setText("Sauvegarder");
        sauvegarder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sauvegarderActionPerformed(evt);
            }
        });
        add(sauvegarder, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 486, -1, 45));

        redm.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        redm.setForeground(new java.awt.Color(255, 0, 0));
        add(redm, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 550, 400, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void prenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prenomActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void sauvegarderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sauvegarderActionPerformed
        Connection connection = null;
        PreparedStatement pst = null;
        try{
            
            connection = DBConnection.openConnection();
            pst = connection.prepareStatement("UPDATE utilisateur set nom = ? , prenom = ? , login = ? , pwd = ? where id_utilisateur = ? ");
            pst.setString(1, nom.getText());
            pst.setString(2, prenom.getText());
            pst.setString(3, login.getText());
            pst.setString(4, password.getText());
            pst.setString(5, user.getId());
            
            pst.executeUpdate();
            user = new Utilisateur(user.getId(),nom.getText(),prenom.getText(),login.getText(),password.getText(),"Etudiant");
            this.updateUser(user);
            redm.setText("Redémarrez l'application pour voir les chanegements");
            revalidate();
            repaint();
            
        }catch(SQLException e ){
            e.getMessage();
        }finally{
            try{
                if(pst!=null){
                    DBConnection.closeConnection();
                    pst.close();
                }                     
            }catch(SQLException e){
                e.getMessage();
            }
        }
        
    }//GEN-LAST:event_sauvegarderActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField login;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField password;
    private javax.swing.JTextField prenom;
    private javax.swing.JLabel redm;
    private javax.swing.JButton sauvegarder;
    // End of variables declaration//GEN-END:variables
}
