/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package BilbioFramesPanels;
import MyClasses.*;
/**
 *
 * @author GLADIATEUR-1650-8
 */
public class SuppLivre extends javax.swing.JPanel {
    private static SuppLivre instance;
    public Utilisateur user;
    /**
     * Creates new form Home
     */
    public SuppLivre(Utilisateur user) {
        initComponents();
        this.user = user;
    }
    public static SuppLivre getInstance(Utilisateur user){
        if(instance !=null){
            return instance;
        }else{
            return new SuppLivre(user);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Supp = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        IDlivre = new javax.swing.JTextField();

        setBackground(new java.awt.Color(102, 102, 102));

        Supp.setText("Supprimer");
        Supp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuppActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID Livre");

        IDlivre.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        IDlivre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDlivreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Supp)
                .addGap(459, 459, 459))
            .addGroup(layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(IDlivre, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(276, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(267, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDlivre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(112, 112, 112)
                .addComponent(Supp)
                .addGap(184, 184, 184))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void IDlivreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDlivreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDlivreActionPerformed

    private void SuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuppActionPerformed
        // TODO add your handling code here:
        Livre.SuppLivre(IDlivre.getText());
        new javax.swing.JOptionPane().showMessageDialog(null, "Livre supprimé avec succé");
    }//GEN-LAST:event_SuppActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDlivre;
    private javax.swing.JButton Supp;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
