package MyFrames;
import BilbioFramesPanels.SuppLivre;
import BilbioFramesPanels.RetLivre;
import BilbioFramesPanels.NotifierUtil;
import BilbioFramesPanels.EmprunterLivre;
import BilbioFramesPanels.BibConsCatalogue;
import BilbioFramesPanels.AjoutLivre;
import EnsEtudFramesPanels.*;
import Menu.*;
import java.awt.Component;
import MyClasses.*;

public class BiblioInterface extends javax.swing.JFrame {
    public static Utilisateur user;
    public BiblioInterface(Utilisateur user) {
        initComponents();
        username.setText(user.getNom()+" "+user.getPrenom());
        
       
        biblioMenu1.setEvent(new MenuEvent(){
            public void selected(int index){
                
                if(index == 0){
                    Dashboard home = Dashboard.getInstance();
                    ShowComp(home);
                }
                else if (index == 1){
                    ProfPar PP = ProfPar.getInstance(user);
                    ShowComp(PP);
                }
                else if (index == 2){
                    BibConsCatalogue CC = BibConsCatalogue.getInstance(user);
                    ShowComp(CC);
                }
                else if (index == 3){
                    AjoutLivre his = AjoutLivre.getInstance(user);
                    ShowComp(his);
                }
                else if (index == 4){
                    SuppLivre his = SuppLivre.getInstance(user);
                    ShowComp(his);
                }
                else if (index == 5){
                    EmprunterLivre EL = EmprunterLivre.getInstance(user);
                    ShowComp(EL);
                }
                else if (index == 6){
                    RetLivre EL = RetLivre.getInstance(user);
                    ShowComp(EL);
                }
                else if (index == 7){
                    NotifierUtil EL = NotifierUtil.getInstance(user);
                    ShowComp(EL);
                }
                else{
                    dispose();
                    Login log = new Login();
                    log.setVisible(true);
                }
            }
        });
        
    }
    public void ShowComp(Component comp){
        Body.removeAll();
        Body.add(comp);
        Body.repaint();
        Body.revalidate();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        scrollPaneWin111 = new Menu.ScrollPaneWin11();
        biblioMenu1 = new Menu.BiblioMenu();
        Header = new javax.swing.JPanel();
        username = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Body = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(72, 92, 93));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrollPaneWin111.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        scrollPaneWin111.setViewportView(biblioMenu1);

        jPanel1.add(scrollPaneWin111, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 74, 230, 600));

        Header.setBackground(new java.awt.Color(60, 60, 60));
        Header.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        username.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/user1.png"))); // NOI18N

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        jPanel1.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 70));

        Body.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Body.setLayout(new java.awt.BorderLayout());
        jPanel1.add(Body, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 74, 1000, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BiblioInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BiblioInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BiblioInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BiblioInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BiblioInterface(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Body;
    private javax.swing.JPanel Header;
    private Menu.BiblioMenu biblioMenu1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private Menu.ScrollPaneWin11 scrollPaneWin111;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
