package MyFrames;

import java.sql.*;
import MyClasses.*;



public class EELogin extends javax.swing.JFrame {

    /**
     * Creates new form LibrarianLogin
     */
    public EELogin() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        libPass = new javax.swing.JPasswordField();
        libUser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        invLog = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EnsEtud Login");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(16, 16, 16));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1161, 672));
        jPanel1.setPreferredSize(new java.awt.Dimension(1140, 672));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        libPass.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        libPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libPassActionPerformed(evt);
            }
        });
        jPanel1.add(libPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 330, 50));

        libUser.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        libUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libUserActionPerformed(evt);
            }
        });
        jPanel1.add(libUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 330, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(46, 90, 240));
        jLabel4.setText("Mot de passe");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(46, 90, 240));
        jLabel5.setText("Login");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, -1));

        LoginButton.setBackground(new java.awt.Color(87, 148, 247));
        LoginButton.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(255, 255, 255));
        LoginButton.setText("Connexion");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        jPanel1.add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 330, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(46, 90, 240));
        jLabel6.setText("Bienvenue");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 130, 50));

        invLog.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        invLog.setForeground(new java.awt.Color(255, 0, 0));
        invLog.setText(" ");
        jPanel1.add(invLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, 280, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1161, 672));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void libPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libPassActionPerformed
        
       
    }//GEN-LAST:event_libPassActionPerformed

    private void libUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_libUserActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        String username = libUser.getText();
        char [] pwdChar = libPass.getPassword();
        String pwd = new String(pwdChar);
        try{
            Connection connection = DBConnection.openConnection();
            String req = "SELECT * FROM utilisateur WHERE login = ? AND pwd = ? AND roles = 'EE'";
            PreparedStatement pstat = connection.prepareStatement(req);
            pstat.setString(1, username);
            pstat.setString(2, pwd);
            ResultSet res = pstat.executeQuery();      
            if (res.next()){
                EnsEtudInterface home = new EnsEtudInterface(new Utilisateur(
                        res.getString("id_utilisateur"),
                        res.getString("nom"),
                        res.getString("prenom"),
                        res.getString("login"),
                        res.getString("pwd"),
                        "Etudiant"
                ));
                home.setVisible(true);
                this.dispose();
                /*this.dispose();*/
                connection.close();
                pstat.close();
                res.close();
            }else{
                String invuserpd = "Connexion echoué. Verifier vos informations!";
                invLog.setText(invuserpd);
                
                
            }
        }catch(Exception e){
            e.printStackTrace();
            System.out.println("Login Error");
        }
        
    }//GEN-LAST:event_LoginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EELogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EELogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EELogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EELogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EELogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel invLog;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField libPass;
    private javax.swing.JTextField libUser;
    // End of variables declaration//GEN-END:variables
}
